<?php

return [
    'iso'		=> [
        'aed'	=> [
            'iso_numeric'			=> '784',
            'name'					=> 'United Arab Emirates Dirham',
            'symbol'				=> 'د.إ',
            'alternate_symbols'		=> ['DH', 'Dhs'],
            'subunit'				=> 'Fils',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'afn' => [
            'iso_numeric'			=> '971',
            'name'					=> 'Afghan Afghani',
            'symbol'				=> '؋',
            'alternate_symbols'		=> ['Af', 'Afs'],
            'subunit'				=> 'Pul',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'all' => [
            'iso_numeric'			=> '008',
            'name'					=> 'Albanian Lek',
            'symbol'				=> 'L',
            'alternate_symbols'		=> ['Lek'],
            'subunit'				=> 'Qintar',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'amd' => [
            'iso_numeric'			=> '051',
            'name'					=> 'Armenian Dram',
            'symbol'				=> 'դր.',
            'alternate_symbols'		=> ['dram'],
            'subunit'				=> 'Luma',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ang' => [
            'iso_numeric'			=> '532',
            'name'					=> 'Netherlands Antillean Gulden',
            'symbol'				=> 'ƒ',
            'alternate_symbols'		=> ['NAƒ', 'NAf', 'f'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x0192;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'aoa' => [
            'iso_numeric'			=> '973',
            'name'					=> 'Angolan Kwanza',
            'symbol'				=> 'Kz',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cêntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ars' => [
            'iso_numeric'			=> '032',
            'name'					=> 'Argentine Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['$m/n', 'm$n'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'aud' => [
            'iso_numeric'			=> '036',
            'name'					=> 'Australian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['A$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'awg' => [
            'iso_numeric'			=> '533',
            'name'					=> 'Aruban Florin',
            'symbol'				=> 'ƒ',
            'alternate_symbols'		=> ['Afl'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x0192;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'azn' => [
            'iso_numeric'			=> '944',
            'name'					=> 'Azerbaijani Manat',
            'symbol'				=> 'm',
            'alternate_symbols'		=> ['man'],
            'subunit'				=> 'Qəpik',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bam' => [
            'iso_numeric'			=> '977',
            'name'					=> 'Bosnia and Herzegovina Convertible Mark',
            'symbol'				=> 'КМ',
            'alternate_symbols'		=> ['KM'],
            'subunit'				=> 'Fening',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bbd' => [
            'iso_numeric'			=> '052',
            'name'					=> 'Barbadian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['Bds$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bdt' => [
            'iso_numeric'			=> '050',
            'name'					=> 'Bangladeshi Taka',
            'symbol'				=> '৳',
            'alternate_symbols'		=> ['Tk'],
            'subunit'				=> 'Paisa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bgn' => [
            'iso_numeric'			=> '975',
            'name'					=> 'Bulgarian Lev',
            'symbol'				=> 'лв',
            'alternate_symbols'		=> ['lev', 'leva', 'лев', 'лева'],
            'subunit'				=> 'Stotinka',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bhd' => [
            'iso_numeric'			=> '048',
            'name'					=> 'Bahraini Dinar',
            'symbol'				=> 'ب.د',
            'alternate_symbols'		=> ['BD'],
            'subunit'				=> 'Fils',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bif' => [
            'iso_numeric'			=> '108',
            'name'					=> 'Burundian Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['FBu'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bmd' => [
            'iso_numeric'			=> '060',
            'name'					=> 'Bermudian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['BD$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bnd' => [
            'iso_numeric'			=> '096',
            'name'					=> 'Brunei Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['B$'],
            'subunit'				=> 'Sen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bob' => [
            'iso_numeric'			=> '068',
            'name'					=> 'Bolivian Boliviano',
            'symbol'				=> 'Bs.',
            'alternate_symbols'		=> ['Bs'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'brl' => [
            'iso_numeric'			=> '986',
            'name'					=> 'Brazilian Real',
            'symbol'				=> 'R$ ',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> 'R$',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'bsd' => [
            'iso_numeric'			=> '044',
            'name'					=> 'Bahamian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['B$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'btn' => [
            'iso_numeric'			=> '064',
            'name'					=> 'Bhutanese Ngultrum',
            'symbol'				=> 'Nu.',
            'alternate_symbols'		=> ['Nu'],
            'subunit'				=> 'Chertrum',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bwp' => [
            'iso_numeric'			=> '072',
            'name'					=> 'Botswana Pula',
            'symbol'				=> 'P',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Thebe',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'byr' => [
            'iso_numeric'			=> '974',
            'name'					=> 'Belarusian Ruble',
            'symbol'				=> 'Br',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Kapyeyka',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'bzd' => [
            'iso_numeric'			=> '084',
            'name'					=> 'Belize Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['BZ$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'cad' => [
            'iso_numeric'			=> '124',
            'name'					=> 'Canadian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['C$', 'CAD$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'cdf' => [
            'iso_numeric'			=> '976',
            'name'					=> 'Congolese Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['FC'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'chf' => [
            'iso_numeric'			=> '756',
            'name'					=> 'Swiss Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['SFr', 'CHF'],
            'subunit'				=> 'Rappen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'clf' => [
            'iso_numeric'			=> '990',
            'name'					=> 'Unidad de Fomento',
            'symbol'				=> 'UF',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Peso',
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'clp' => [
            'iso_numeric'			=> '152',
            'name'					=> 'Chilean Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Peso',
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'cny' => [
            'iso_numeric'			=> '156',
            'name'					=> 'Chinese Renminbi Yuan',
            'symbol'				=> '¥',
            'alternate_symbols'		=> ['CN¥', '元', 'CN元'],
            'subunit'				=> 'Fen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x5713;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'cop' => [
            'iso_numeric'			=> '170',
            'name'					=> 'Colombian Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['COL$'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'crc' => [
            'iso_numeric'			=> '188',
            'name'					=> 'Costa Rican Colón',
            'symbol'				=> '₡',
            'alternate_symbols'		=> ['¢'],
            'subunit'				=> 'Céntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'cuc' => [
            'iso_numeric'			=> '931',
            'name'					=> 'Cuban Convertible Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['CUC$'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'cup' => [
            'iso_numeric'			=> '192',
            'name'					=> 'Cuban Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['$MN'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'cve' => [
            'iso_numeric'			=> '132',
            'name'					=> 'Cape Verdean Escudo',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['Esc'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'czk' => [
            'iso_numeric'			=> '203',
            'name'					=> 'Czech Koruna',
            'symbol'				=> 'Kč',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Haléř',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'djf' => [
            'iso_numeric'			=> '262',
            'name'					=> 'Djiboutian Franc',
            'symbol'				=> 'Fdj',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'dkk' => [
            'iso_numeric'			=> '208',
            'name'					=> 'Danish Krone',
            'symbol'				=> 'kr',
            'alternate_symbols'		=> [',-'],
            'subunit'				=> 'Øre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'dop' => [
            'iso_numeric'			=> '214',
            'name'					=> 'Dominican Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['RD$'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'dzd' => [
            'iso_numeric'			=> '012',
            'name'					=> 'Algerian Dinar',
            'symbol'				=> 'د.ج',
            'alternate_symbols'		=> ['DA'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'egp' => [
            'iso_numeric'			=> '818',
            'name'					=> 'Egyptian Pound',
            'symbol'				=> 'ج.م',
            'alternate_symbols'		=> ['LE', 'E£', 'L.E.'],
            'subunit'				=> 'Piastre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ern' => [
            'iso_numeric'			=> '232',
            'name'					=> 'Eritrean Nakfa',
            'symbol'				=> 'Nfk',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'etb' => [
            'iso_numeric'			=> '230',
            'name'					=> 'Ethiopian Birr',
            'symbol'				=> 'Br',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Santim',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'eur' => [
            'iso_numeric'			=> '978',
            'name'					=> 'Euro',
            'symbol'				=> '€',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20AC;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'fjd' => [
            'iso_numeric'			=> '242',
            'name'					=> 'Fijian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['FJ$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'fkp' => [
            'iso_numeric'			=> '238',
            'name'					=> 'Falkland Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> ['FK£'],
            'subunit'				=> 'Penny',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gbp' => [
            'iso_numeric'			=> '826',
            'name'					=> 'British Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Penny',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gel' => [
            'iso_numeric'			=> '981',
            'name'					=> 'Georgian Lari',
            'symbol'				=> 'ლ',
            'alternate_symbols'		=> ['lari'],
            'subunit'				=> 'Tetri',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ghs' => [
            'iso_numeric'			=> '936',
            'name'					=> 'Ghanaian Cedi',
            'symbol'				=> '₵',
            'alternate_symbols'		=> ['GH¢', 'GH₵'],
            'subunit'				=> 'Pesewa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B5;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gip' => [
            'iso_numeric'			=> '292',
            'name'					=> 'Gibraltar Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Penny',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gmd' => [
            'iso_numeric'			=> '270',
            'name'					=> 'Gambian Dalasi',
            'symbol'				=> 'D',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Butut',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gnf' => [
            'iso_numeric'			=> '324',
            'name'					=> 'Guinean Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['FG', 'GFr'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gtq' => [
            'iso_numeric'			=> '320',
            'name'					=> 'Guatemalan Quetzal',
            'symbol'				=> 'Q',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'gyd' => [
            'iso_numeric'			=> '328',
            'name'					=> 'Guyanese Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['G$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'hkd' => [
            'iso_numeric'			=> '344',
            'name'					=> 'Hong Kong Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['HK$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'hnl' => [
            'iso_numeric'			=> '340',
            'name'					=> 'Honduran Lempira',
            'symbol'				=> 'L',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'hrk' => [
            'iso_numeric'			=> '191',
            'name'					=> 'Croatian Kuna',
            'symbol'				=> 'kn',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Lipa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'htg' => [
            'iso_numeric'			=> '332',
            'name'					=> 'Haitian Gourde',
            'symbol'				=> 'G',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'huf' => [
            'iso_numeric'			=> '348',
            'name'					=> 'Hungarian Forint',
            'symbol'				=> 'Ft',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Fillér',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'idr' => [
            'iso_numeric'			=> '360',
            'name'					=> 'Indonesian Rupiah',
            'symbol'				=> 'Rp',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Sen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'ils' => [
            'iso_numeric'			=> '376',
            'name'					=> 'Israeli New Sheqel',
            'symbol'				=> '₪',
            'alternate_symbols'		=> ['ש״ח', 'NIS'],
            'subunit'				=> 'Agora',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20AA;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'inr' => [
            'iso_numeric'			=> '356',
            'name'					=> 'Indian Rupee',
            'symbol'				=> '₹',
            'alternate_symbols'		=> ['Rs', '৳', '૱', '௹', 'रु', '₨', ],
            'subunit'				=> 'Paisa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20b9;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'iqd' => [
            'iso_numeric'			=> '368',
            'name'					=> 'Iraqi Dinar',
            'symbol'				=> 'ع.د',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Fils',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'irr' => [
            'iso_numeric'			=> '364',
            'name'					=> 'Iranian Rial',
            'symbol'				=> '﷼',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Dinar',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#xFDFC;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'isk' => [
            'iso_numeric'			=> '352',
            'name'					=> 'Icelandic Króna',
            'symbol'				=> 'kr',
            'alternate_symbols'		=> ['Íkr'],
            'subunit'				=> 'Eyrir',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'jmd' => [
            'iso_numeric'			=> '388',
            'name'					=> 'Jamaican Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['J$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'jod' => [
            'iso_numeric'			=> '400',
            'name'					=> 'Jordanian Dinar',
            'symbol'				=> 'د.ا',
            'alternate_symbols'		=> ['JD'],
            'subunit'				=> 'Piastre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'jpy' => [
            'iso_numeric'			=> '392',
            'name'					=> 'Japanese Yen',
            'symbol'				=> '¥',
            'alternate_symbols'		=> ['円', '圓'],
            'subunit'				=> NULL,
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A5;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kes' => [
            'iso_numeric'			=> '404',
            'name'					=> 'Kenyan Shilling',
            'symbol'				=> 'KSh',
            'alternate_symbols'		=> ['Sh'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kgs' => [
            'iso_numeric'			=> '417',
            'name'					=> 'Kyrgyzstani Som',
            'symbol'				=> 'som',
            'alternate_symbols'		=> ['сом'],
            'subunit'				=> 'Tyiyn',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'khr' => [
            'iso_numeric'			=> '116',
            'name'					=> 'Cambodian Riel',
            'symbol'				=> '៛',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Sen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x17DB;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kmf' => [
            'iso_numeric'			=> '174',
            'name'					=> 'Comorian Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['CF'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kpw' => [
            'iso_numeric'			=> '408',
            'name'					=> 'North Korean Won',
            'symbol'				=> '₩',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Chŏn',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20A9;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'krw' => [
            'iso_numeric'			=> '410',
            'name'					=> 'South Korean Won',
            'symbol'				=> '₩',
            'subunit'				=> NULL,
            'subunit_to_unit'		=> 1,
            'alternate_symbols'		=> [],
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A9;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kwd' => [
            'iso_numeric'			=> '414',
            'name'					=> 'Kuwaiti Dinar',
            'symbol'				=> 'د.ك',
            'alternate_symbols'		=> ['K.D.'],
            'subunit'				=> 'Fils',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kyd' => [
            'iso_numeric'			=> '136',
            'name'					=> 'Cayman Islands Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['CI$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'kzt' => [
            'iso_numeric'			=> '398',
            'name'					=> 'Kazakhstani Tenge',
            'symbol'				=> '〒',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Tiyn',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'lak' => [
            'iso_numeric'			=> '418',
            'name'					=> 'Lao Kip',
            'symbol'				=> '₭',
            'alternate_symbols'		=> ['₭N'],
            'subunit'				=> 'Att',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20AD;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'lbp' => [
            'iso_numeric'			=> '422',
            'name'					=> 'Lebanese Pound',
            'symbol'				=> 'ل.ل',
            'alternate_symbols'		=> ['£', 'L£'],
            'subunit'				=> 'Piastre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'lkr' => [
            'iso_numeric'			=> '144',
            'name'					=> 'Sri Lankan Rupee',
            'symbol'				=> '₨',
            'alternate_symbols'		=> ['රු', 'ரூ', 'SLRs', '/-'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x0BF9;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'lrd' => [
            'iso_numeric'			=> '430',
            'name'					=> 'Liberian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['L$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],


        'lsl' => [
            'iso_numeric'			=> '426',
            'name'					=> 'Lesotho Loti',
            'symbol'				=> 'L',
            'alternate_symbols'		=> ['M'],
            'subunit'				=> 'Sente',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],


        'ltl' => [
            'iso_numeric'			=> '440',
            'name'					=> 'Lithuanian Litas',
            'symbol'				=> 'Lt',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centas',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],


        'lvl' => [
            'iso_numeric'			=> '428',
            'name'					=> 'Latvian Lats',
            'symbol'				=> 'Ls',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Santīms',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],


        'lyd' => [
            'iso_numeric'			=> '434',
            'name'					=> 'Libyan Dinar',
            'symbol'				=> 'ل.د',
            'alternate_symbols'		=> ['LD'],
            'subunit'				=> 'Dirham',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],


        'mad' => [
            'iso_numeric'			=> '504',
            'name'					=> 'Moroccan Dirham',
            'symbol'				=> 'DH',
            'alternate_symbols'		=> ['د.م.'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mdl' => [
            'iso_numeric'			=> '498',
            'name'					=> 'Moldovan Leu',
            'symbol'				=> 'L',
            'alternate_symbols'		=> ['lei'],
            'subunit'				=> 'Ban',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mga' => [
            'iso_numeric'			=> '969',
            'name'					=> 'Malagasy Ariary',
            'symbol'				=> 'Ar',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Iraimbilanja',
            'subunit_to_unit'		=> 5,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mkd' => [
            'iso_numeric'			=> '807',
            'name'					=> 'Macedonian Denar',
            'symbol'				=> 'ден',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Deni',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mmk' => [
            'iso_numeric'			=> '104',
            'name'					=> 'Myanmar Kyat',
            'symbol'				=> 'K',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Pya',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mnt' => [
            'iso_numeric'			=> '496',
            'name'					=> 'Mongolian Tögrög',
            'symbol'				=> '₮',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Möngö',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20AE;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mop' => [
            'iso_numeric'			=> '446',
            'name'					=> 'Macanese Pataca',
            'symbol'				=> 'P',
            'alternate_symbols'		=> ['MOP$'],
            'subunit'				=> 'Avo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mro' => [
            'iso_numeric'			=> '478',
            'name'					=> 'Mauritanian Ouguiya',
            'symbol'				=> 'UM',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Khoums',
            'subunit_to_unit'		=> 5,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mur' => [
            'iso_numeric'			=> '480',
            'name'					=> 'Mauritian Rupee',
            'symbol'				=> '₨',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A8;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mvr' => [
            'iso_numeric'			=> '462',
            'name'					=> 'Maldivian Rufiyaa',
            'symbol'				=> 'MVR',
            'alternate_symbols'		=> ['MRF', 'Rf', '/-', 'ރ'],
            'subunit'				=> 'Laari',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mwk' => [
            'iso_numeric'			=> '454',
            'name'					=> 'Malawian Kwacha',
            'symbol'				=> 'MK',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Tambala',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mxn' => [
            'iso_numeric'			=> '484',
            'name'					=> 'Mexican Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['MEX$'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'myr' => [
            'iso_numeric'			=> '458',
            'name'					=> 'Malaysian Ringgit',
            'symbol'				=> 'RM',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Sen',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'mzn' => [
            'iso_numeric'			=> '943',
            'name'					=> 'Mozambican Metical',
            'symbol'				=> 'MTn',
            'alternate_symbols'		=> ['MZN'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'nad' => [
            'iso_numeric'			=> '516',
            'name'					=> 'Namibian Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['N$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ngn' => [
            'iso_numeric'			=> '566',
            'name'					=> 'Nigerian Naira',
            'symbol'				=> '₦',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Kobo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20A6;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'nio' => [
            'iso_numeric'			=> '558',
            'name'					=> 'Nicaraguan Córdoba',
            'symbol'				=> 'C$',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'nok' => [
            'iso_numeric'			=> '578',
            'name'					=> 'Norwegian Krone',
            'symbol'				=> 'kr',
            'alternate_symbols'		=> [',-'],
            'subunit'				=> 'Øre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> 'kr',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'npr' => [
            'iso_numeric'			=> '524',
            'name'					=> 'Nepalese Rupee',
            'symbol'				=> '₨',
            'alternate_symbols'		=> ['Rs', 'रू'],
            'subunit'				=> 'Paisa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A8;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'nzd' => [
            'iso_numeric'			=> '554',
            'name'					=> 'New Zealand Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['NZ$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'omr' => [
            'iso_numeric'			=> '512',
            'name'					=> 'Omani Rial',
            'symbol'				=> 'ر.ع.',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Baisa',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> true,
            'html_entity'			=> '&#xFDFC;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'pab' => [
            'iso_numeric'			=> '590',
            'name'					=> 'Panamanian Balboa',
            'symbol'				=> 'B/.',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Centésimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'pen' => [
            'iso_numeric'			=> '604',
            'name'					=> 'Peruvian Nuevo Sol',
            'symbol'				=> 'S/.',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Céntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> 'S/.',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'pgk' => [
            'iso_numeric'			=> '598',
            'name'					=> 'Papua New Guinean Kina',
            'symbol'				=> 'K',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Toea',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'php' => [
            'iso_numeric'			=> '608',
            'name'					=> 'Philippine Peso',
            'symbol'				=> '₱',
            'alternate_symbols'		=> ['PHP', 'PhP', 'P'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'pkr' => [
            'iso_numeric'			=> '586',
            'name'					=> 'Pakistani Rupee',
            'symbol'				=> '₨',
            'alternate_symbols'		=> ['Rs'],
            'subunit'				=> 'Paisa',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A8;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'pln' => [
            'iso_numeric'			=> '985',
            'name'					=> 'Polish Złoty',
            'symbol'				=> 'zł',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Grosz',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> 'z&#322;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> ' ',
        ],

        'pyg' => [
            'iso_numeric'			=> '600',
            'name'					=> 'Paraguayan Guaraní',
            'symbol'				=> '₲',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Céntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B2;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'qar' => [
            'iso_numeric'			=> '634',
            'name'					=> 'Qatari Riyal',
            'symbol'				=> 'ر.ق',
            'alternate_symbols'		=> ['QR'],
            'subunit'				=> 'Dirham',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#xFDFC;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ron' => [
            'iso_numeric'			=> '946',
            'name'					=> 'Romanian Leu',
            'symbol'				=> 'Lei',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Bani',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'rsd' => [
            'iso_numeric'			=> '941',
            'name'					=> 'Serbian Dinar',
            'symbol'				=> 'РСД',
            'alternate_symbols'		=> ['RSD', 'din', 'дин'],
            'subunit'				=> 'Para',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'rub' => [
            'iso_numeric'			=> '643',
            'name'					=> 'Russian Ruble',
            'symbol'				=> 'р.',
            'alternate_symbols'		=> ['руб'],
            'subunit'				=> 'Kopek',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x0440;&#x0443;&#x0431;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'rwf' => [
            'iso_numeric'			=> '646',
            'name'					=> 'Rwandan Franc',
            'symbol'				=> 'FRw',
            'alternate_symbols'		=> ['RF', 'R₣'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sar' => [
            'iso_numeric'			=> '682',
            'name'					=> 'Saudi Riyal',
            'symbol'				=> 'ر.س',
            'alternate_symbols'		=> ['SR', '﷼'],
            'subunit'				=> 'Hallallah',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#xFDFC;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sbd' => [
            'iso_numeric'			=> '090',
            'name'					=> 'Solomon Islands Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['SI$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'scr' => [
            'iso_numeric'			=> '690',
            'name'					=> 'Seychellois Rupee',
            'symbol'				=> '₨',
            'alternate_symbols'		=> ['SRe', 'SR'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20A8;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sdg' => [
            'iso_numeric'			=> '938',
            'name'					=> 'Sudanese Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Piastre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sek' => [
            'iso_numeric'			=> '752',
            'name'					=> 'Swedish Krona',
            'symbol'				=> 'kr',
            'alternate_symbols'		=> [':-'],
            'subunit'				=> 'Öre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> ' ',
        ],

        'sgd' => [
            'iso_numeric'			=> '702',
            'name'					=> 'Singapore Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['S$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'shp' => [
            'iso_numeric'			=> '654',
            'name'					=> 'Saint Helenian Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Penny',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'skk' => [
            'iso_numeric'			=> '703',
            'name'					=> 'Slovak Koruna',
            'symbol'				=> 'Sk',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Halier',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sll' => [
            'iso_numeric'			=> '694',
            'name'					=> 'Sierra Leonean Leone',
            'symbol'				=> 'Le',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'sos' => [
            'iso_numeric'			=> '706',
            'name'					=> 'Somali Shilling',
            'symbol'				=> 'Sh',
            'alternate_symbols'		=> ['Sh.So'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'srd' => [
            'iso_numeric'			=> '968',
            'name'					=> 'Surinamese Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ssp' => [
            'iso_numeric'			=> '728',
            'name'					=> 'South Sudanese Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'piaster',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'std' => [
            'iso_numeric'			=> '678',
            'name'					=> 'São Tomé and Príncipe Dobra',
            'symbol'				=> 'Db',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cêntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'svc' => [
            'iso_numeric'			=> '222',
            'name'					=> 'Salvadoran Colón',
            'symbol'				=> '₡',
            'alternate_symbols'		=> ['¢'],
            'subunit'				=> 'Centavo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20A1;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'syp' => [
            'iso_numeric'			=> '760',
            'name'					=> 'Syrian Pound',
            'symbol'				=> '£S',
            'alternate_symbols'		=> ['£', 'ل.س', 'LS', 'الليرة السورية'],
            'subunit'				=> 'Piastre',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'szl' => [
            'iso_numeric'			=> '748',
            'name'					=> 'Swazi Lilangeni',
            'symbol'				=> 'L',
            'alternate_symbols'		=> ['E'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'thb' => [
            'iso_numeric'			=> '764',
            'name'					=> 'Thai Baht',
            'symbol'				=> '฿',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Satang',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x0E3F;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'tjs' => [
            'iso_numeric'			=> '972',
            'name'					=> 'Tajikistani Somoni',
            'symbol'				=> 'ЅМ',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Diram',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'tmt' => [
            'iso_numeric'			=> '934',
            'name'					=> 'Turkmenistan manat',
            'symbol'				=> 'm',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Tennesi',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'tnd' => [
            'iso_numeric'			=> '788',
            'name'					=> 'Tunisian Dinar',
            'symbol'				=> 'د.ت',
            'alternate_symbols'		=> ['TD', 'DT'],
            'subunit'				=> 'Millime',
            'subunit_to_unit'		=> 1000,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'top' => [
            'iso_numeric'			=> '776',
            'name'					=> 'Tongan Paʻanga',
            'symbol'				=> 'T$',
            'alternate_symbols'		=> ['PT'],
            'subunit'				=> 'Seniti',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'try' => [
            'iso_numeric'			=> '949',
            'name'					=> 'Turkish Lira',
            'symbol'				=> 'TL',
            'alternate_symbols'		=> [],
            'subunit'				=> 'kuruş',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'ttd' => [
            'iso_numeric'			=> '780',
            'name'					=> 'Trinidad and Tobago Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['TT$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'twd' => [
            'iso_numeric'			=> '901',
            'name'					=> 'New Taiwan Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['NT$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'tzs' => [
            'iso_numeric'			=> '834',
            'name'					=> 'Tanzanian Shilling',
            'symbol'				=> 'Sh',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'uah' => [
            'iso_numeric'			=> '980',
            'name'					=> 'Ukrainian Hryvnia',
            'symbol'				=> '₴',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Kopiyka',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#x20B4',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'ugx' => [
            'iso_numeric'			=> '800',
            'name'					=> 'Ugandan Shilling',
            'symbol'				=> 'USh',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'usd' => [
            'iso_numeric'			=> '840',
            'name'					=> 'United States Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['US$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'uyu' => [
            'iso_numeric'			=> '858',
            'name'					=> 'Uruguayan Peso',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['$U'],
            'subunit'				=> 'Centésimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20B1;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'uzs' => [
            'iso_numeric'			=> '860',
            'name'					=> 'Uzbekistani Som',
            'symbol'				=> 'som',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Tiyin',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'vef' => [
            'iso_numeric'			=> '937',
            'name'					=> 'Venezuelan Bolívar',
            'symbol'				=> 'Bs F',
            'alternate_symbols'		=> ['Bs.F', 'Bs'],
            'subunit'				=> 'Céntimo',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'vnd' => [
            'iso_numeric'			=> '704',
            'name'					=> 'Vietnamese Đồng',
            'symbol'				=> '₫',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Hào',
            'subunit_to_unit'		=> 10,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x20AB;',
            'decimal_mark'			=> ',',
            'thousands_separator'	=> '.',
        ],

        'vuv' => [
            'iso_numeric'			=> '548',
            'name'					=> 'Vanuatu Vatu',
            'symbol'				=> 'Vt',
            'alternate_symbols'		=> [],
            'subunit'				=> NULL,
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'wst' => [
            'iso_numeric'			=> '882',
            'name'					=> 'Samoan Tala',
            'symbol'				=> 'T',
            'alternate_symbols'		=> ['WS$', 'SAT', 'ST'],
            'subunit'				=> 'Sene',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xaf' => [
            'iso_numeric'			=> '950',
            'name'					=> 'Central African Cfa Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['FCFA'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xag' => [
            'iso_numeric'			=> '961',
            'name'					=> 'Silver (Troy Ounce)',
            'symbol'				=> 'oz t',
            'alternate_symbols'		=> [],
            'subunit'				=> 'oz',
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xau' => [
            'iso_numeric'			=> '959',
            'name'					=> 'Gold (Troy Ounce)',
            'symbol'				=> 'oz t',
            'alternate_symbols'		=> [],
            'subunit'				=> 'oz',
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xcd' => [
            'iso_numeric'			=> '951',
            'name'					=> 'East Caribbean Dollar',
            'symbol'				=> '$',
            'alternate_symbols'		=> ['EC$'],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xdr' => [
            'iso_numeric'			=> '960',
            'name'					=> 'Special Drawing Rights',
            'symbol'				=> 'SDR',
            'alternate_symbols'		=> ['XDR'],
            'subunit'				=> '',
            'subunit_to_unit'		=> 1,
            'symbol_first'			=> false,
            'html_entity'			=> '$',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xof' => [
            'iso_numeric'			=> '952',
            'name'					=> 'West African Cfa Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['CFA'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'xpf' => [
            'iso_numeric'			=> '953',
            'name'					=> 'Cfp Franc',
            'symbol'				=> 'Fr',
            'alternate_symbols'		=> ['F'],
            'subunit'				=> 'Centime',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'yer' => [
            'iso_numeric'			=> '886',
            'name'					=> 'Yemeni Rial',
            'symbol'				=> '﷼',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Fils',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '&#xFDFC;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'zar' => [
            'iso_numeric'			=> '710',
            'name'					=> 'South African Rand',
            'symbol'				=> 'R',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Cent',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x0052;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'zmk' => [
            'iso_numeric'			=> '894',
            'name'					=> 'Zambian Kwacha',
            'symbol'				=> 'ZK',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Ngwee',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'zmw' => [
            'iso_numeric'			=> '967',
            'name'					=> 'Zambian Kwacha',
            'symbol'				=> 'ZK',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Ngwee',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> false,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],
    ],

    'no-iso'	=> [
        'btc' => [
            'iso_numeric'			=> '',
            'name'					=> 'Bitcoin',
            'symbol'				=> '฿',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Satoshi',
            'subunit_to_unit'		=> 100000000,
            'symbol_first'			=> true,
            'html_entity'			=> '',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ],

        'jep' => [
            'iso_numeric'			=> '',
            'name'					=> 'Jersey Pound',
            'symbol'				=> '£',
            'alternate_symbols'		=> [],
            'subunit'				=> 'Penny',
            'subunit_to_unit'		=> 100,
            'symbol_first'			=> true,
            'html_entity'			=> '&#x00A3;',
            'decimal_mark'			=> '.',
            'thousands_separator'	=> ',',
        ]
    ]
];
